#!/usr/bin/env python3
"""
inject_lang_switcher.py
========================

Phase 4-a: Inserts a uniform language switcher anchor into JA↔EN paired
pages. Idempotent — safe to re-run; existing managed snippets are
detected via marker comments and skipped.

Spec reference: i18n project handover §3.1 / spec §7.2.

Behavior summary
----------------
- Reads the canonical paired-page list from scripts/i18n_config.py
  (JA_EN_PAIRS).
- For each pair, edits both HTML files to insert a small <a> link
  pointing at the other-language counterpart, located in the page
  header.
- Sets a `preferred_locale` cookie on click (one-year expiry, SameSite=Lax)
  for future analytics or opt-in personalization. **No automatic redirect
  is implemented** — Google explicitly forbids that.
- Preserves accessibility: aria-label, keyboard-focusable.
- Adds rel="alternate" + hreflang on the anchor.

Usage
-----
    # Dry-run (default): prints planned changes, writes nothing.
    python3 scripts/inject_lang_switcher.py --dry-run

    # Apply changes:
    python3 scripts/inject_lang_switcher.py

    # Apply only to a subset (path glob match against the canonical
    # JA-side path stored in JA_EN_PAIRS):
    python3 scripts/inject_lang_switcher.py --only "/captio-alternative/"

    # Verbose:
    python3 scripts/inject_lang_switcher.py -v

Idempotency contract
--------------------
The injected block is delimited by:

    <!-- lang-switcher:begin (managed by inject_lang_switcher.py) -->
    ...
    <!-- lang-switcher:end -->

On re-run, the script:
  1. If markers are present, the block is regenerated in-place
     (so future template changes propagate cleanly).
  2. If markers are absent, a new block is inserted at the chosen
     anchor (see ANCHOR_PATTERNS below).
  3. If neither markers nor an anchor are found, the file is skipped
     and a warning is printed (so the operator can extend
     ANCHOR_PATTERNS without surprises).

Anchor selection
----------------
Anchors are tried in order; the first match wins. All matchers operate
on raw HTML text (regex), not a DOM tree, to keep the script
dependency-free.

Tested anchor candidates:

  1. Inside the existing `<div class="lang-dropdown">…</div>` block
     (homepage style — replaces the dropdown's first <a> position).
     -> NOT used for paired pages; we coexist beside it.
  2. Just before `</nav>` of the primary nav.
  3. Just before `</header>`.
  4. Just after the opening `<header>` tag.

The matcher prefers (2) → (3) → (4) for paired pages, so the switcher
sits in the navigation row.

Cookie
------
On click, the anchor sets `preferred_locale=<locale>` with
`max-age=31536000` (1 year), `path=/`, `SameSite=Lax`. The cookie is
informational only — there is no automatic redirect anywhere in the
site.

Failure modes & exit codes
--------------------------
- Returns 0 even if some files were skipped. The summary at the end
  lists skipped files.
- Returns 2 only on hard errors (e.g. i18n_config import failed).

Author: Generated by Cowork session 2026-05-01.
"""

from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path
from typing import NamedTuple


# --- Configuration --------------------------------------------------

# Project root is two levels up from scripts/inject_lang_switcher.py
# when run from a checked-out repo. Override via --repo-root CLI flag
# if running from elsewhere.
DEFAULT_REPO_ROOT = Path(__file__).resolve().parent.parent

MARKER_BEGIN = "<!-- lang-switcher:begin (managed by inject_lang_switcher.py) -->"
MARKER_END = "<!-- lang-switcher:end -->"

# Anchor patterns, tried in priority order. Each entry is
# (description, compiled_regex_with_named_group_'before').
# The matched pattern's index 0 must end exactly at the position where
# we want to insert the new block. We use a positive lookahead so the
# match has zero width and we can splice in cleanly.
ANCHOR_PATTERNS: list[tuple[str, re.Pattern]] = [
    (
        "before </nav>",
        re.compile(r"(?P<indent>[ \t]*)(?=</nav>)"),
    ),
    (
        "before </header>",
        re.compile(r"(?P<indent>[ \t]*)(?=</header>)"),
    ),
    (
        "after <header...>",
        re.compile(r"<header\b[^>]*>(?P<indent>\s*)"),
    ),
]

# Map from i18n locale slug to display label and aria text.
# Keep labels short (1-2 words). They show inline in the header.
LOCALE_LABELS: dict[str, dict[str, str]] = {
    "ja": {"label": "日本語", "aria_to": "日本語ページに切り替え"},
    "en": {"label": "English", "aria_to": "Switch to English"},
}


# --- Data types -----------------------------------------------------

class Pair(NamedTuple):
    ja_path: str   # repo-relative or root-relative URL fragment, e.g. "/captio-alternative/"
    en_path: str
    ja_file: Path  # absolute or repo-relative HTML file
    en_file: Path


class Result(NamedTuple):
    file: Path
    locale_self: str   # "ja" or "en"
    locale_other: str
    other_url: str
    action: str   # "inserted" | "regenerated" | "unchanged" | "skipped:no-anchor" | "skipped:missing"
    detail: str = ""


# --- I/O helpers ----------------------------------------------------

def url_to_html_path(repo_root: Path, url: str) -> Path:
    """
    Map a site-relative URL like "/captio-alternative/" or "/privacy"
    to the actual HTML file on disk. Tries common conventions:
      - "/foo/"  -> repo_root/foo/index.html
      - "/foo"   -> repo_root/foo.html or repo_root/foo/index.html
    Returns the first existing path or the canonical "/index.html"
    candidate (so caller can decide skip vs error).
    """
    rel = url.lstrip("/")
    if rel.endswith("/") or rel == "":
        candidate = repo_root / rel / "index.html"
    else:
        # Try .html sibling first, then directory/index.html
        flat = repo_root / f"{rel}.html"
        if flat.exists():
            return flat
        candidate = repo_root / rel / "index.html"
    return candidate


def load_pairs(repo_root: Path) -> list[Pair]:
    """Import JA_EN_PAIRS from scripts/i18n_config.py and resolve to disk paths."""
    sys.path.insert(0, str(repo_root / "scripts"))
    try:
        import i18n_config  # type: ignore[import-not-found]
    except ModuleNotFoundError as e:  # pragma: no cover
        print(
            f"ERROR: cannot import scripts/i18n_config.py from {repo_root}: {e}",
            file=sys.stderr,
        )
        sys.exit(2)
    pairs: list[Pair] = []
    for ja_url, en_url in i18n_config.JA_EN_PAIRS:
        pairs.append(
            Pair(
                ja_path=ja_url,
                en_path=en_url,
                ja_file=url_to_html_path(repo_root, ja_url),
                en_file=url_to_html_path(repo_root, en_url),
            )
        )
    return pairs


# --- Snippet builder -----------------------------------------------

def build_snippet(self_locale: str, other_locale: str, other_url: str) -> str:
    """Produce the wrapped, idempotent-marked switcher HTML block."""
    other = LOCALE_LABELS[other_locale]
    aria_label = other["aria_to"]
    label = other["label"]
    # Use double quotes for HTML attrs; embed the cookie write via onclick.
    # SameSite=Lax is appropriate for a preference cookie.
    cookie_write = (
        f"document.cookie='preferred_locale={other_locale};"
        f"path=/;max-age=31536000;SameSite=Lax'"
    )
    inner = (
        f'<a class="lang-switcher-link" '
        f'href="{other_url}" '
        f'rel="alternate" '
        f'hreflang="{other_locale}" '
        f'data-locale-from="{self_locale}" '
        f'data-locale-to="{other_locale}" '
        f'aria-label="{aria_label}" '
        f'onclick="{cookie_write}">'
        f'{label}'
        f'</a>'
    )
    return f"{MARKER_BEGIN}\n{inner}\n{MARKER_END}"


# --- Edit logic -----------------------------------------------------

MARKER_BLOCK_RE = re.compile(
    re.escape(MARKER_BEGIN) + r".*?" + re.escape(MARKER_END),
    re.DOTALL,
)


def edit_html(
    html: str,
    self_locale: str,
    other_locale: str,
    other_url: str,
    *,
    verbose: bool = False,
) -> tuple[str, str]:
    """
    Returns (new_html, action). action is one of:
      'unchanged'   — block already correct, no diff
      'regenerated' — block existed and was rewritten
      'inserted'    — no block existed and one was inserted at anchor
      'skipped:no-anchor' — could not find any anchor; html unchanged
    """
    snippet = build_snippet(self_locale, other_locale, other_url)

    # Case 1: existing managed block — regenerate in place
    if MARKER_BEGIN in html:
        new_html = MARKER_BLOCK_RE.sub(snippet, html, count=1)
        if new_html == html:
            return html, "unchanged"
        return new_html, "regenerated"

    # Case 2: no marker yet — insert at first matching anchor
    for desc, pat in ANCHOR_PATTERNS:
        m = pat.search(html)
        if m:
            indent = m.groupdict().get("indent") or ""
            # Insert snippet, with leading newline + matching indent for
            # cosmetic continuity. We splice right after the match end
            # (which is zero-width for lookahead-based patterns, or
            # immediately after <header...> for the third pattern).
            insertion = f"\n{indent}{snippet}\n{indent}"
            new_html = html[: m.end()] + insertion + html[m.end():]
            if verbose:
                print(f"  anchor used: {desc}")
            return new_html, "inserted"

    return html, "skipped:no-anchor"


# --- Driver ---------------------------------------------------------

def process_pair(
    pair: Pair,
    *,
    dry_run: bool,
    verbose: bool,
    only: str | None,
) -> list[Result]:
    if only and only not in pair.ja_path and only not in pair.en_path:
        return []
    results: list[Result] = []
    targets = [
        ("ja", "en", pair.ja_file, pair.en_path),
        ("en", "ja", pair.en_file, pair.ja_path),
    ]
    for self_loc, other_loc, file_path, other_url in targets:
        if not file_path.exists():
            results.append(
                Result(
                    file=file_path,
                    locale_self=self_loc,
                    locale_other=other_loc,
                    other_url=other_url,
                    action="skipped:missing",
                    detail="file not found",
                )
            )
            continue
        original = file_path.read_text(encoding="utf-8")
        new_html, action = edit_html(
            original, self_loc, other_loc, other_url, verbose=verbose,
        )
        if action in ("inserted", "regenerated") and not dry_run:
            file_path.write_text(new_html, encoding="utf-8")
        results.append(
            Result(
                file=file_path,
                locale_self=self_loc,
                locale_other=other_loc,
                other_url=other_url,
                action=action,
            )
        )
    return results


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(
        description="Inject language switcher into paired HTML pages.",
    )
    parser.add_argument(
        "--repo-root",
        type=Path,
        default=DEFAULT_REPO_ROOT,
        help="Repo root (default: parent of this script's directory).",
    )
    parser.add_argument(
        "--dry-run",
        action="store_true",
        help="Print planned changes; write no files.",
    )
    parser.add_argument(
        "--only",
        default=None,
        help="Substring filter on the JA or EN URL path. "
             "Example: --only '/captio-alternative/'",
    )
    parser.add_argument("-v", "--verbose", action="store_true")
    args = parser.parse_args(argv)

    pairs = load_pairs(args.repo_root)
    print(f"Loaded {len(pairs)} JA↔EN pairs from i18n_config.JA_EN_PAIRS")
    if args.only:
        print(f"  --only filter active: {args.only!r}")
    if args.dry_run:
        print("  DRY-RUN: no files will be written")
    print()

    all_results: list[Result] = []
    for pair in pairs:
        all_results.extend(
            process_pair(
                pair,
                dry_run=args.dry_run,
                verbose=args.verbose,
                only=args.only,
            )
        )

    # Summary table
    counts: dict[str, int] = {}
    for r in all_results:
        counts[r.action] = counts.get(r.action, 0) + 1

    print(f"{'file':<60} {'self':<5} {'->':<3} {'other':<5} {'action'}")
    print("-" * 90)
    for r in all_results:
        rel = str(r.file)
        if len(rel) > 58:
            rel = "…" + rel[-57:]
        print(
            f"{rel:<60} {r.locale_self:<5} -> {r.locale_other:<5} "
            f"{r.action}{(' (' + r.detail + ')') if r.detail else ''}"
        )

    print()
    print("Summary: " + ", ".join(f"{k}={v}" for k, v in sorted(counts.items())))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
