import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
import { createHash } from 'node:crypto';
import { execFileSync } from 'node:child_process';
import { fileURLToPath } from 'node:url';
import { load, validate } from './autopilot-runs.mjs';
const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const read = name => fs.readFileSync(path.join(root, name), 'utf8');
const write = (name, value) => { const file = path.join(root, name); fs.mkdirSync(path.dirname(file), {recursive:true}); fs.writeFileSync(file, value); };
const blob = text => createHash('sha1').update(`blob ${Buffer.byteLength(text)}\0`).update(text).digest('hex');
const id = 'ap-20260916-owner-session-pagespeed';
const proofPath = 'docs/perf/owner-session-recovery-20260917.json';
const before = load();
if (before.runs.some(r => r.run_id === id)) throw Error('Already recovered; do not duplicate');
assert.equal(blob(read('data/autopilot-runs.json')), '73e705c8cb3bc8a78c0d1a86b781368d7f825bf8');
assert.equal(blob(read('data/autopilot-status.json')), '610588ee2b937fddb4a6dd52a800da220ec71358');
assert.equal(blob(read('autopilot/index.html')), 'b4e82eaad72ca546b6f042d71cb1875ee8271fd0');
assert(!before.runs.some(r => [1425,1426].includes(r.pr)), 'Do not count an existing shipment again');
const evidence = JSON.parse(read('owner-performance-evidence.json'));
assert.equal(evidence.pr.number,1426); assert.equal(evidence.pr.merged,true);
assert.equal(evidence.pr.merge_commit_sha,'f752e80b5bebd05e75e755885c9c6e44e314b304');
assert.equal(new Date(Date.parse(evidence.pr.merged_at)+9*3600000).toISOString().slice(0,10),'2026-09-16');
assert.equal(evidence.audit.id,35097287925); assert.equal(evidence.audit.conclusion,'success');
assert.equal(evidence.audit.head_sha,evidence.pr.merge_commit_sha);
assert.equal(evidence.seo.id,35097287853); assert.equal(evidence.seo.conclusion,'success');
assert.equal(evidence.seo.head_sha,evidence.pr.merge_commit_sha);
assert.equal(evidence.artifact.id,10446718605);
assert.equal(evidence.artifact.digest,'sha256:0f0487511f0ddcc4bf563119bb4e91d84b7fafbc998497a7b6408b99e36e8ff0');
const receipt = JSON.parse(read('owner-performance-receipt.json'));
assert.equal(receipt.verified,true); assert.equal(receipt.commit,evidence.pr.merge_commit_sha);
assert.equal(receipt.checked_at,'2026-09-16T12:42:31.820Z');
assert.equal(Object.keys(receipt.assets).length,32);
assert(Object.values(receipt.pages).every(p => p.status===200 && p.matches_checkout===true));
const runArgs = ['scripts/autopilot-runs.mjs','--append','--run-id',id,'--date','2026-09-16','--route','owner-session','--outcome','shipped','--attempted','true','--lane','F','--action','repair','--pr','1426','--external-ref','github-pr:1425+1426','--source','session'];
execFileSync(process.execPath, runArgs, {cwd:root,stdio:'inherit'});
const doc=load(), row=doc.runs.find(r=>r.run_id===id);
row.interventions=[{kind:'request',note:'オーナーのPageSpeed改善・マージ・公開指示による作業。定期起動・自然起票・無介入の成功には数えない。'}];
row.note='PR1425と追加PR1426を同じPageSpeed改善サイクルとして1行で回収。2026-09-16に両方公開済み。監査PR1431や未採用実験は出荷数に含めない。ローカルCodex定期タスクの未取得記録・成否は依然不明。';
row.evidence=proofPath;
assert.deepEqual(validate(doc),[]);
assert.deepEqual(doc.runs.filter(r=>r.run_id!==id),before.runs,'Prior records must remain unchanged');
write('data/autopilot-runs.json',JSON.stringify(doc,null,2)+'\n');
const status=JSON.parse(read('data/autopilot-status.json'));
status.previous_scheduled_observation={date_jst:status.date_jst,source:'https://github.com/simplememofast/simplememo/blob/993828cae21d5a63a2efd1e6e6b325fde3e46e13/data/autopilot-status.json',action:status.action,article:status.article,pr:status.pr,reason:status.reason,verified:status.verified,checks:status.checks,next:status.next};
status.date_jst='2026-09-16'; status.generated_at=new Date().toISOString(); status.action='repair'; status.article=null; status.pr=1426;
status.observation_scope='Recovered owner-requested PageSpeed maintenance, not a scheduled run; unknown local scheduler outcomes remain unknown.';
status.data_freshness={...status.data_freshness,as_of_date_jst:'2026-09-15',refreshed_in_this_session:false};
status.cost={...status.cost,as_of_date_jst:'2026-09-15',refreshed_in_this_session:false};
status.streak={...status.streak,consecutive_no_article_days:2,last_production_change_date_jst:'2026-09-16',days_since_production_change:0};
status.reason='2026-09-16のオーナー依頼によるホームページ高速化を、既存の公開証拠から運転台帳へ回収。PR1425/1426は1改善サイクル、Lane Fの保守として計上。定期運転の成功、記事公開、無介入出荷とは扱わない。';
status.verified='PR1426のマージ、同一SHAのPageSpeed Audit・SEO Validation成功、公開2ページと32ファイルの照合証跡を確認。証拠: '+proofPath+'。9月16〜17日の未取得ローカル定期タスク結果は不明のまま。';
status.checks={seo_check:'PR1426 main-push SEO Validation 35097287853 succeeded; reconciliation PR CI pending.',mobile_qa:'PR1426 audit 35097287925: 18 local and 18 production browser scenarios passed.',scheduled_run_recovery:'Not verified. No new success/failure/no_run outcome is inferred for local Codex schedules.'};
status.next='監査改良PR1431は統合CI成功後にマージする。未取得の定期実行記録は一次証拠が得られるまで不明として保持。以前の実験重複による保留と未解決の運用課題は previous_scheduled_observation.next に保存し、解除しない。';
write('data/autopilot-status.json',JSON.stringify(status,null,2)+'\n');
execFileSync(process.execPath,['scripts/autopilot-runs.mjs','--write-status'],{cwd:root,stdio:'inherit'});
execFileSync(process.execPath,['scripts/decision-monitor.mjs','--publish-report'],{cwd:root,stdio:'inherit'});
let html=read('autopilot/index.html');
const marker='<!-- run-streaks:end -->'; assert.equal(html.split(marker).length,2);
html=html.replace(marker,marker+'\n          9月16日の記録はオーナー依頼による高速化保守です。定期運転の成功や記事公開を意味せず、同日の未取得タスク結果は不明のままです。');
html=html.replace(/("dateModified"\s*:\s*")[^"]+"/g,(_,prefix)=>prefix+'2026-09-17"');
write('autopilot/index.html',html);
const updateDate=(file,tag,url)=>{let n=0;const text=read(file).replace(new RegExp(`<${tag}>[\\s\\S]*?<\\/${tag}>`,'g'),b=>{if(!b.includes(`<loc>${url}</loc>`))return b;n++;return b.replace(/<lastmod>[^<]*<\/lastmod>/,'<lastmod>2026-09-17</lastmod>');});assert.equal(n,1);write(file,text);};
updateDate('sitemap-ja.xml','url','https://simplememofast.com/autopilot/');
updateDate('sitemap.xml','sitemap','https://simplememofast.com/sitemap-ja.xml');
const proof={recorded_at:status.generated_at,observed_work_date_jst:'2026-09-16',run_id:id,scope:'One owner-requested maintenance cycle, counted once. No claim about scheduled or unknown local tasks.',...evidence,deployment_receipt:receipt,unresolved:'Unknown scheduled task outcomes remain unknown; this recovery does not establish their completion.'};
write(proofPath,JSON.stringify(proof,null,2)+'\n');
console.log('Recovered one proven owner-requested shipment; prior ledger rows, cost snapshot, thresholds and unknown outcomes preserved.');
